react-week1-homework
qamarfj/hyf-homework pull request #24
Opened 2021-02-22 16:16 UTC by qamarfj

2021-02-23 05:55 UTC, braedongough approved these changes
Great work! No major feedback 😄

2021-02-23 05:55 UTC, braedongough commented on react/week1/todo/src/ToDo.js
> +      <h3> {title}</h3>
```suggestion
      <h3>{title}</h3>
```

2021-02-23 05:55 UTC, braedongough commented on react/week1/todo/src/ToDo.js
> +export const ToDo = ({ title, deadLine }) => {
```suggestion
export const Todo = ({ title, deadLine }) => {
```

I wonder consider renaming this to keep it consistent with your Todos component.

2021-02-26 16:54 UTC, Ekamba requested changes
Hi @qamarfj , like @braedongough said your work is good. But remember  when you are are rendering a list of items you have to specify a key. You can read more about it here: https://reactjs.org/docs/lists-and-keys.html

2021-02-28 21:34 UTC, merged