React/week3
qamarfj/hyf-homework pull request #26
Opened 2021-03-08 11:23 UTC by qamarfj

2021-03-08 21:06 UTC, obelitz requested changes
Nice! 👍 
You have that one `todos` import that fails when I run the code.

2021-03-08 21:06 UTC, obelitz commented on react/week3/todos/src/App.js
> +import Todos from "./Todos";
It seems like you named the component file `todos.js` but you're importing `Todos.js` here

2021-03-08 21:06 UTC, obelitz commented on react/week3/todos/src/Border.js
> +  return <div className="border">{props.children}</div>;
You use PascalCase for your other component classes, so I'd do the same thing here: `className="Border"`

2021-03-08 21:06 UTC, obelitz commented on react/week3/todos/src/TodosList.js
> +    <li className={isCheked ? "Done" : "notDone"}>
You are not using the `notDone` for currently, so you could use an empty string:
```suggestion
    <li className={isCheked ? "Done" : ""}>
```
or use `&&`

2021-03-08 21:06 UTC, obelitz commented on react/week3/todos/src/TodosList.js
> +  todo: PropTypes.object,
If you know the values you're getting in an object, you can go even further and use the proptype `shape`. 
```
todo: PropTypes.shape({
  prop: PropTypes.whateverType,
  someOtherProp: PropTypes.someOtherType
})
```
See more here: https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes

2021-03-08 21:06 UTC, obelitz commented on react/week3/todos/src/todos.js
> +          setCurrentTodos((prev) => prev.concat(todos));
Nice with using the `concat` here

2021-03-08 21:06 UTC, obelitz commented on react/week3/todos/src/todos.js
> +  function AddTodo(e) {
I'd use camelCase for these three functions

2021-03-08 21:06 UTC, obelitz commented on react/week3/todos/src/todos.js
> +    setCurrentTodos(todos.filter((todo) => todo.id !== id));
Nice use of the `filter` method

2021-03-08 21:06 UTC, obelitz commented on react/week3/todos/src/todos.js
> +  }
Great thinking with this validation.

If you want, you can use backticks \` for string interpolation here:
```
const currentDate = `${now.getFullYear()}-${month}-${day}`
```

2021-03-09 15:21 UTC, qamarfj commented on react/week3/todos/src/App.js
> +import Todos from "./Todos";
Thank you for your valuable feedback and precious time you have putt on to review my home work. I have fixed the file name.

2021-03-15 07:24 UTC, merged